# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7325143204b42b6fa5f0abf408cec00b20a1eb70590a789281d4624a0d9a4d7f9a873ddffa3ba290225dd91d021e1d4dfd921bdee199f77d29a97bec8fb6852

test:
  secret_key_base: 7f044d8a79f8ec5abdc07494a2ff70b1367a008d59d345dc1a7a29336fbae9d451419422bcbb49a7632ce745598ede16ef7f43fbfee0cc50376d668e4ecadb18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
